//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shuttle.OAuth {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shuttle.OAuth.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find an &apos;access_token&apos; property in the returned data.  Received: {0}.
        /// </summary>
        public static string AccessTokenNotFoundException {
            get {
                return ResourceManager.GetString("AccessTokenNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No code challenge found for method &apos;{0}&apos;..
        /// </summary>
        public static string CodeChallengeNotFoundException {
            get {
                return ResourceManager.GetString("CodeChallengeNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IOAuthProvider with name &apos;{0}&apos; has already been registered..
        /// </summary>
        public static string DuplicateProviderException {
            get {
                return ResourceManager.GetString("DuplicateProviderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuthOptions with name &apos;{0}&apos; has not been registered..
        /// </summary>
        public static string MissingOptionsException {
            get {
                return ResourceManager.GetString("MissingOptionsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IOAuthProvider with name &apos;{0}&apos; has not been registered..
        /// </summary>
        public static string MissingProviderException {
            get {
                return ResourceManager.GetString("MissingProviderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content is `null`..
        /// </summary>
        public static string NullContentException {
            get {
                return ResourceManager.GetString("NullContentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a data item with name &apos;{0}&apos;..
        /// </summary>
        public static string OAuthGrantDataNameNotFoundException {
            get {
                return ResourceManager.GetString("OAuthGrantDataNameNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No grant found with id &apos;{0}&apos;..
        /// </summary>
        public static string OAuthGrantNotFoundException {
            get {
                return ResourceManager.GetString("OAuthGrantNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an OAuthProviderOptions instance with an empty name..
        /// </summary>
        public static string OAuthProivderOptionsNameException {
            get {
                return ResourceManager.GetString("OAuthProivderOptionsNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find an OAuthProviderOptions instance with name &apos;{0}&apos;..
        /// </summary>
        public static string OAuthProviderOptionsNotFoundException {
            get {
                return ResourceManager.GetString("OAuthProviderOptionsNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; must be provided..
        /// </summary>
        public static string OptionRequired {
            get {
                return ResourceManager.GetString("OptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client Id must be provided..
        /// </summary>
        public static string OptionsClientIdRequired {
            get {
                return ResourceManager.GetString("OptionsClientIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client secret must be provided..
        /// </summary>
        public static string OptionsClientSecretRequired {
            get {
                return ResourceManager.GetString("OptionsClientSecretRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The options name must be provided..
        /// </summary>
        public static string OptionsNameRequired {
            get {
                return ResourceManager.GetString("OptionsNameRequired", resourceCulture);
            }
        }
    }
}
